-- MySQL Script generated by MySQL Workbench
-- jue 19 sep 2019 23:23:33 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controlpedido
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controlpedido
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlpedido` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `controlpedido` ;

-- -----------------------------------------------------
-- Table `controlpedido`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlpedido`.`cliente` (
  `idcliente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'listado de clientes de SF';


-- -----------------------------------------------------
-- Table `controlpedido`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlpedido`.`vendedor` (
  `idvendedor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idvendedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'lista de vendedores San Fernando';


-- -----------------------------------------------------
-- Table `controlpedido`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlpedido`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `idnota` INT NULL,
  `idfac` INT NULL,
  `fecha` DATE NULL,
  `cliente` INT NULL,
  `vendedor` INT NULL,
  PRIMARY KEY (`idpedido`),
  UNIQUE INDEX `idnota_UNIQUE` (`idnota` ASC),
  UNIQUE INDEX `idfac_UNIQUE` (`idfac` ASC),
  UNIQUE INDEX `vendedor_UNIQUE` (`vendedor` ASC),
  UNIQUE INDEX `cliente_UNIQUE` (`cliente` ASC),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `controlpedido`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor`
    FOREIGN KEY (`vendedor`)
    REFERENCES `controlpedido`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'tabla principal';


-- -----------------------------------------------------
-- Table `controlpedido`.`personalalmacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlpedido`.`personalalmacen` (
  `idpersonalalmacen` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersonalalmacen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'personal de almacen encargados de la preparacion';


-- -----------------------------------------------------
-- Table `controlpedido`.`fallo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlpedido`.`fallo` (
  `idfallo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idfallo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'listado de tipo de fallos en la preparacion';


-- -----------------------------------------------------
-- Table `controlpedido`.`preparacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlpedido`.`preparacion` (
  `idpreparacion` INT NOT NULL,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `picking` INT NULL,
  `revision` INT NULL,
  `fallo` INT NULL,
  `idpedido` INT NULL,
  PRIMARY KEY (`idpreparacion`),
  UNIQUE INDEX `idpedido_UNIQUE` (`idpedido` ASC),
  INDEX `fk_preparacion_1_idx` (`picking` ASC),
  INDEX `fk_preparacion_1_idx1` (`revision` ASC),
  UNIQUE INDEX `picking_UNIQUE` (`picking` ASC),
  UNIQUE INDEX `revision_UNIQUE` (`revision` ASC),
  INDEX `fk_preparacion_2_idx` (`fallo` ASC),
  CONSTRAINT `fk_preparacion_pedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `controlpedido`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preparacion_picking`
    FOREIGN KEY (`picking`)
    REFERENCES `controlpedido`.`personalalmacen` (`idpersonalalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preparacion_revision`
    FOREIGN KEY (`revision`)
    REFERENCES `controlpedido`.`personalalmacen` (`idpersonalalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preparacion_fallo`
    FOREIGN KEY (`fallo`)
    REFERENCES `controlpedido`.`fallo` (`idfallo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'tabla de pedidos preparados';


-- -----------------------------------------------------
-- Table `controlpedido`.`despachador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlpedido`.`despachador` (
  `iddespachador` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`iddespachador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'responsables de la entrega del pedido al cliente';


-- -----------------------------------------------------
-- Table `controlpedido`.`despacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlpedido`.`despacho` (
  `iddespacho` INT NOT NULL,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `iddespachador` INT NULL,
  `idpedido` INT NULL,
  PRIMARY KEY (`iddespacho`),
  UNIQUE INDEX `idpedido_UNIQUE` (`idpedido` ASC),
  UNIQUE INDEX `iddespachador_UNIQUE` (`iddespachador` ASC),
  CONSTRAINT `fk_despacho_pedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `controlpedido`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despacho_despachador`
    FOREIGN KEY (`iddespachador`)
    REFERENCES `controlpedido`.`despachador` (`iddespachador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'registro de los despachos de los pedidos';


-- -----------------------------------------------------
-- Table `controlpedido`.`transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlpedido`.`transporte` (
  `idtransporte` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idtransporte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'listado de transporte para envios de pedidos';


-- -----------------------------------------------------
-- Table `controlpedido`.`destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlpedido`.`destino` (
  `iddestino` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`iddestino`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'listado de destinos, distribuidores, cadenas de farmacias, etc';


-- -----------------------------------------------------
-- Table `controlpedido`.`envios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlpedido`.`envios` (
  `idenvios` INT NOT NULL,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `transporte` INT NULL,
  `destino` INT NULL,
  `guia` VARCHAR(45) NULL,
  `iddespacho` INT NULL,
  PRIMARY KEY (`idenvios`),
  UNIQUE INDEX `transporte_UNIQUE` (`transporte` ASC),
  UNIQUE INDEX `destino_UNIQUE` (`destino` ASC),
  UNIQUE INDEX `iddespacho_UNIQUE` (`iddespacho` ASC),
  CONSTRAINT `fk_envios_despacho`
    FOREIGN KEY (`iddespacho`)
    REFERENCES `controlpedido`.`despacho` (`iddespacho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_envios_destino`
    FOREIGN KEY (`destino`)
    REFERENCES `controlpedido`.`destino` (`iddestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_envios_transporte`
    FOREIGN KEY (`transporte`)
    REFERENCES `controlpedido`.`transporte` (`idtransporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'detalle de envios nacionales, locales, etc';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
